### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by mindboggling**
Complete react section

### CODE REVIEW

**Review by kyusulamita — CHANGES_REQUESTED** [review]
- change folder name from 'assets' to 'public'
- delete server/start.js file

**Comment by mindboggling** [comment]
made requested changes

**Review by kyusulamita — CHANGES_REQUESTED** [review]
-get rid of index.html on root folder

**Review by kyusulamita — APPROVED** [review]
Great job 🍡

**Pull request merged**
